#!/usr/bin/env bash

git_info() {
  git rev-parse --is-inside-work-tree &>/dev/null || return
  local branch=$(git symbolic-ref -q HEAD | sed -e 's|^refs/heads/||')
  local dirty=$(git diff --quiet --ignore-submodules HEAD &>/dev/null; [ $? -eq 1 ] && echo -e "*")

  echo " (${branch}${dirty})"
}
